Board
tine-krueger/connect-four pull request #6
Opened 2021-03-12 15:13 UTC by tine-krueger

2021-03-13 09:37 UTC, lennart-sakowsky commented on src/services/initialiseBoard.js
> +export function initialBoard() {
I think it would be better to stick with one and the same name for file and function:
initializeBoard – with a z.

2021-03-13 09:40 UTC, lennart-sakowsky requested changes

2021-03-13 09:40 UTC, lennart-sakowsky commented on src/services/initialiseBoard.js
> +}
The test file initializeBoard.test.js could look like this:

```
import { initializeBoard } from "./initializeBoard";

describe("initializeBoard", () => {
  it("should return an array with 7 nested arrays, each containing 6 zeros", () => {
    const expectedArray = [
      [0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0],
    ];
    const initialArray = initialBoard();
    expect(initialArray).toStrictEqual(expectedArray);
  });
});
```

2021-03-13 14:33 UTC, tine-krueger commented on src/services/initialiseBoard.js
> +}
looks good! What about testing the component and if it is shown the right way?

2021-03-14 11:02 UTC, lennart-sakowsky approved these changes
I had time to check it now, it renders correctly. I have written tests for App.js which I am going to push right away.
To query I used data-testid – at this stage of development I think it's okay to do so.

2021-03-16 08:31 UTC, tine-krueger commented on src/App.test.js
> +});
Great!

2021-03-16 08:47 UTC, merged